const Import = {
    img1: require("../assets/asset 0.png"),
    img2: require("../assets/asset 1.svg"),
    img3: require("../assets/asset 2.svg"),
    img4: require("../assets/asset 3.png"), 
    img5: require("../assets/asset 4.svg"),
    img6: require("../assets/asset 5.png"),
    img7: require("../assets/asset 6.png"),
    img8: require("../assets/asset 7.png"),
    img9: require("../assets/asset 8.svg"),
    img10: require("../assets/asset 9.svg"),
    img11: require("../assets/asset 10.png"),
    img12: require("../assets/asset 11.svg"),
    img13: require("../assets/asset 12.png"),
    img14: require("../assets/asset 13.png"),
    img15: require("../assets/asset 14.svg"),
    img16: require("../assets/asset 15.png"),
    img17: require("../assets/asset 16.svg"),
    img18: require("../assets/asset 17.svg"),
    img19: require("../assets/asset 18.svg"),
    img20: require("../assets/asset 19.svg"),
    img21: require("../assets/asset 20.png"),
    img22: require("../assets/asset 21.png"),
    img23: require("../assets/asset 22.png"),
    img24: require("../assets/asset 23.png"),
    img25: require("../assets/asset 24.svg"),
    img26: require("../assets/asset 25.svg"),
    img27: require("../assets/asset 26.svg"),
    img28: require("../assets/asset 27.svg"),
    img29: require("../assets/asset 28.svg"),
    img30: require("../assets/asset 29.svg"),
    img45: require("../assets/asset 30.svg"),
    img31: require("../assets/asset 31.svg"),
    img32: require("../assets/asset 32.svg"),
    img33: require("../assets/asset 33.svg"),
    img34: require("../assets/asset 34.svg"),
    img35: require("../assets/asset 35.svg"),
    img36: require("../assets/asset 36.svg"),
    img37: require("../assets/asset 37.svg"),
    img38: require("../assets/asset 38.svg"),
    img39: require("../assets/asset 39.svg"),
    img40: require("../assets/asset 40.svg"),
    img41: require("../assets/asset 41.svg"),
    img42: require("../assets/asset 42.svg"),
    img43: require("../assets/asset 43.svg"),
    img44: require("../assets/asset 44.svg"),


};

export default Import;
